/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Pj_Concessionaria;

import java.awt.Image;
import javax.swing.ImageIcon;

/**
 *
 * @author Tales
 */
public class CarroBasico extends javax.swing.JFrame {
    
    private final TelaInicial telaInicial;

    /**
     * Creates new form CarroBasico
     */
    public CarroBasico(TelaInicial telaInicial) {
        initComponents();
        this.telaInicial = telaInicial;
        exibirImagem();
    }

    private CarroBasico() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

        
    private void exibirImagem(){
        ImageIcon originalPegeout = new ImageIcon("src/Imagens/pegeoutDoisZeroOito.png");
        Image imagePegeout = originalPegeout.getImage().getScaledInstance(lblBasicOne.getWidth(), lblBasicOne.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon newImagePegeout = new ImageIcon(imagePegeout);
        lblBasicOne.setIcon(newImagePegeout);
        
        ImageIcon originalCQuatro = new ImageIcon("src/Imagens/citroenC4.png");
        Image imageCQuatro = originalCQuatro.getImage().getScaledInstance(lblBasicTwo.getWidth(), lblBasicTwo.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon newImageCQuatro = new ImageIcon(imageCQuatro);
        lblBasicTwo.setIcon(newImageCQuatro);
        
        ImageIcon originalClassic = new ImageIcon("src/Imagens/corsaClassic.png");
        Image imageClassic = originalClassic.getImage().getScaledInstance(lblBasicThree.getWidth(), lblBasicThree.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon newImageClassic = new ImageIcon(imageClassic);
        lblBasicThree.setIcon(newImageClassic);
        
        ImageIcon originalCivic = new ImageIcon("src/Imagens/hondaCivic.png");
        Image imageCivic = originalCivic.getImage().getScaledInstance(lblBasicFour.getWidth(), lblBasicFour.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon newImageCivic = new ImageIcon(imageCivic);
        lblBasicFour.setIcon(newImageCivic);
        
        ImageIcon originalGol = new ImageIcon("src/Imagens/volkswagenGol.png");
        Image imageGol = originalGol.getImage().getScaledInstance(lblBasicFive.getWidth(), lblBasicFive.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon newImageGol = new ImageIcon(imageGol);
        lblBasicFive.setIcon(newImageGol);
        
        ImageIcon originalLogan = new ImageIcon("src/Imagens/renaultLogan.png");
        Image imageLogan = originalLogan.getImage().getScaledInstance(lblBasicSix.getWidth(), lblBasicSix.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon newImageLogan = new ImageIcon(imageLogan);
        lblBasicSix.setIcon(newImageLogan);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblBasicThree = new javax.swing.JLabel();
        lblBasicOne = new javax.swing.JLabel();
        lblBasicFour = new javax.swing.JLabel();
        lblBasicTwo = new javax.swing.JLabel();
        lblBasicFive = new javax.swing.JLabel();
        lblBasicSix = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblBasicFour, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 114, Short.MAX_VALUE)
                        .addComponent(lblBasicFive, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(175, 175, 175))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblBasicOne, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblBasicTwo, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(135, 135, 135)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblBasicThree, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblBasicSix, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(70, 70, 70))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(180, 180, 180)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblBasicOne, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblBasicThree, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblBasicTwo, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(212, 212, 212)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblBasicFive, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblBasicFour, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblBasicSix, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(196, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CarroBasico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CarroBasico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CarroBasico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CarroBasico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CarroBasico().setVisible(true);
            }
        });
    }
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblBasicFive;
    private javax.swing.JLabel lblBasicFour;
    private javax.swing.JLabel lblBasicOne;
    private javax.swing.JLabel lblBasicSix;
    private javax.swing.JLabel lblBasicThree;
    private javax.swing.JLabel lblBasicTwo;
    // End of variables declaration//GEN-END:variables
}
